### ISSUE TITLE
No Touch Support

### ISSUE THREAD

**Issue by fooloomanzii** [leaflet-extras/leaflet-map#37] opened 2015-07-24 05:17 UTC
Somehow moving in the maps is not possible by touchscreen, also not in development-tools in chrome and firefox. Might has something to do with "tap" in polymer?

**Comment by nhnb** [comment] 2015-07-27 01:27
I cannot reproduce issues regarding moving the map on Chrome or Firefox on Android. Does the issue occur on http://leaflet-extras.github.io/leaflet-map/demo.html , too?

**Comment by nhnb** [comment] 2015-09-29 21:59
Closing as not reproducible.

**Closed by nhnb** 2015-09-29 21:59 UTC
