### ISSUE TITLE
When I use leaflet-map inside another dom element it cannot understand the tile layer urls

### ISSUE THREAD

**Issue by JustinCase1089** [leaflet-extras/leaflet-map#22] opened 2015-06-18 09:09 UTC
Try and place the leaflet map in another element with a leaflet-tilelayer pointing to 
https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
It will fail with
GET https://%7Bs%7D.tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png net::ERR_NAME_NOT_RESOLVED
So it seems it is replacing the {}'s

**Comment by nhnb** [comment] 2015-06-18 23:36
Hello Justin, I am sorry, I cannot reproduce the issue. 

* Does the [tile layer demo](https://leaflet-extras.github.io/leaflet-map/demo.html#tilelayer) work for you?
* Which browsers are affected?
* I am not sure, if I understood "in another element" correctly. Is that just a "div" or a specific element?
* Please provide some sample code that shows the issue.

**Comment by JustinCase1089** [comment] 2015-06-19 06:09
Hi 

I mean in another element like below. Not sure where the best way of posting a code snippet is, but here goes :-)

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script type="text/javascript" src="../webcomponentsjs/webcomponents-lite.min.js"></script>
        <link rel="import" href="leaflet-map.html">
        <link rel="import" href="../iron-ajax/iron-ajax.html">

        <style type="text/css">
            leaflet-map {
                width: 1000px;
                height: 1000px;
            }
        </style>
    </head>
    <body>
        <dom-module id="geojson-sample">
            <template>
                <leaflet-map latitude="0.3516" longitude="102.304" zoom="6">
                    <leaflet-tilelayer 
                        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" maxZoom="18">
                            Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, 
                            <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, 
                            Imagery &copy; <a href="http://mapbox.com">Mapbox</a>
                    </leaflet-tilelayer>
                     <template is="dom-bind">
                      <iron-ajax url="demo-geojson.json" last-response="{{data}}" auto>
                      </iron-ajax>
                      <leaflet-geojson data="[[data]]"></leaflet-geojson>
                    </template>
                </leaflet-map>
            </template>
        </dom-module>
        <script>
        Polymer({
            is: "geojson-sample"
        });
        </script>
        <geojson-sample></geojson-sample>
    </body>
</html>

**Comment by JustinCase1089** [comment] 2015-06-19 06:14
it stripped away the imports in the post, but I am sure they are easy to add. 
If you take the leaflet-map tag and move it outside og the geojson-sample dom-module it works

**Comment by JustinCase1089** [comment] 2015-06-20 18:38
Have you managed to reproduce it?

**Comment by JustinCase1089** [comment] 2015-06-27 09:56
I know it is not pretty, but how about allowing use of []'s in the url which you then replace with {}'s. Then at least the property can be used

**Comment by nhnb** [comment] 2015-07-15 23:12
minimal workaround was released as 1.0.2

**Closed by nhnb** 2015-07-15 23:12 UTC
